[package]
name = "rust-web-sample"
version = "0.1.0"
edition = "2024"

[dependencies]
axum="0.6.16"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4", features = ["fs", "trace", "compression-br"] }